version: '3.8'

services:
  marketing-content:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:80"
    depends_on:
      - marketing-content-db
      - rabbitmq
    env_file:
      - ./env_files/marketing_content.env
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload

  marketing-content-db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase

  marketing-communication:
    build: ../marketingcommunication/.
    ports:
      - "5002:80"
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./env_files/marketing_communication.env

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  rabbitmq_data:
