version: '3.8'

services:
  cart:
    build: ./cart/.
    ports:
      - "5004:5000"
    environment:
      - dbURL=mysql+mysqlconnector://root:password@cart-db:3306/proj_cart
    depends_on:
      - cart-db

  cart-db:
    image: mysql:5.7
    ports:
      - "6004:3306"
    environment:
      MYSQL_DATABASE: proj_cart
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data4:/var/lib/mysql
  order:
    build: ./orders/.
    ports:
      - "5002:5000"
    environment:
      - dbURL=mysql+mysqlconnector://root:password@order-db:3306/proj_order
    depends_on:
      - order-db

  order-db:
    image: mysql:5.7
    ports:
      - "6002:3306"
    environment:
      MYSQL_DATABASE: proj_order
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data2:/var/lib/mysql

  inventory:
    build: ./inventory/.
    ports:
      - "5001:5000"
    environment:
      - dbURL=mysql+mysqlconnector://root:password@inventory-db:3306/proj_inventory
    depends_on:
      - inventory-db

  inventory-db:
    image: mysql:5.7
    ports:
      - "6001:3306"
    environment:
      MYSQL_DATABASE: proj_inventory
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql

  marketing-content:
    build: ./marketingcontent/.
    volumes:
      - ./marketingcontent/.:/usr/src/app
    ports:
      - "8000:80"
    depends_on:
      - marketing-content-db
      - rabbitmq
    env_file:
      - ./env_files/marketing_content.env
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload

  marketing-content-db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase

  marketing-communication:
    build: ./marketingcommunication/.
    ports:
      - "5003:80"
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./env_files/marketing_communication.env

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  rabbitmq_data:
  db-data:
  db-data2:
  db-data4:
