version: '3.8'

services:
  inventory:
    build: .
    ports:
      - "5001:5000"
    environment:
      - dbURL=mysql+mysqlconnector://root:password@inventory-db:3306/proj_inventory
    depends_on:
      - inventory-db
  inventory-db:
    image: mysql:5.7
    ports:
      - "6001:3306"
    environment:
      MYSQL_DATABASE: proj_inventory
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
